### ISSUE TITLE
 DD4T.Mvc.Controllers.DD4TControllerBase.GetPage is throwing below error intermittently

### ISSUE THREAD

**Issue by kpmrafeeq** [dd4t/DD4T.Core#100]
I am getting below error intermittently, not able to find the cause of it. but this is happening at least thrice in a week. 
             ...      System.NullReferenceException (Newtonsoft.Json)
             ...      Object reference not set to an instance of an object.
             ...         at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
             ...         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(JsonContract contract, JsonConverter memberConverter, JsonContainerContract containerContract, JsonProperty containerProperty)
             ...         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
             ...         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
             ...         at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
             ...         at DD4T.Serialization.JSONSerializerService.Deserialize[T](String input)
             ...         at DD4T.Factories.PageFactory.GetIPageObject(String pageStringContent)
             ...         at DD4T.Factories.PageFactory.TryFindPage(String url, IPage& page)
             ...         at DD4T.Mvc.Controllers.DD4TControllerBase.GetPage(String url)
             ...         at Indivirtual.Flydubai.Web.Controllers.PageController.PageData(String url)
             ...         at lambda_method(Closure , ControllerBase , Object[] )
             ...         at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
             ...         at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
             ...         at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
             ...         at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
             ...         at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
             ...         at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
             ...         at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by quirijnslings** [comment]
Could this be related to https://github.com/JamesNK/Newtonsoft.Json/issues/231?

**Comment by quirijnslings** [comment]
Which NewtonSoft version are you on?

**Comment by kpmrafeeq** [comment]
We are using 6.0.8, Do you think we should upgrade the to the latest version? or anybody else reported same issue?

**Comment by NicoEsterhuyse** [comment]
We are seeing the exact same issue, happens about twice a month. Currently using NewtonSoft 7.0.1
@kpmrafeeq - were you able to solve/manage the problem?

**Comment by kpmrafeeq** [comment]
@nicoezterhuyse sorry for late response.. I still see the issue.. it's occuring rarely..

**Comment by quirijnslings** [comment]
I wonder if this snippet is actually threadsafe:

`        public JsonSerializer Serializer
        {
            get
            {
                if (_serializer == null)
                {
                    _serializer = new JsonSerializer
                    {
                        NullValueHandling = NullValueHandling.Ignore
                    };
                    _serializer.Converters.Add(new FieldConverter());
                    _serializer.Converters.Add(new FieldSetConverter());
                }

                return _serializer;
            }
        }`

If you have more than one render thread, could this blow up at all? Should we lock this bit of code?

**Comment by phizhuk-itechart** [comment]
We experience the same issue with the same call stack mentioned above. We use DD4T 2.1.0 packages in our app and NewtonSoft.Json 9.0.1. The issue happens from time to time. We didn't notice any exact pattern of its appearing but most often it happens after deployment. Some time after it usually goes away.
So any help will be appreciated.

**Comment by quirijnslings** [comment]
By the way, it seems to occur in templates as well as in the web application. So it must be something in the serializer (or the model itself, but that seems less likely). The stack trace confirms this.

Does anyone have a stack trace with line numbers?

**Comment by arthurtheaquaboy** [comment]
Here is a recent stack trace captured from Application Insigts on the CD side
https://www.screencast.com/t/HGviA1iwhpD

**Comment by avmgan** [comment]
Still, this issue happening on during the caching refresh or deployment time after the app pool recycle.

**Comment by quirijnslings** [comment]
We upgraded to NewtonSoft.JSON 10.0.1. If you upgrade DD4T to 2.2, does the error go away?

**Comment by kpmrafeeq** [comment]
Let me try

**Comment by avmgan** [comment]
Hi Guys,
We have upgraded sharjah24 solution to DD4T 2.2.3 latest version went Live yesterday (03-Apr-2017) both PROD / Staging.

Today (04-Apr-2017) staging website we received these error message seems to be latest **Newtonsoft.Json.dll 10.0.1.20720**  version not resolving that issue.

14:19:05.88  Error    Handle Section At Error occured at HandleSectionErrorAttribute handling - Error occured at Newtonsoft.Json.JsonSerializer : GetMatchingConverter and Handling (http://preview.sharjah24.ae/en/arts/ by 213.42.204.49)
             ...      System.NullReferenceException (Newtonsoft.Json)
             ...      Object reference not set to an instance of an object.
             ...         at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
             ...         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetConverter(JsonContract contract, JsonConverter memberConverter, JsonContainerContract containerContract, JsonProperty containerProperty)
             ...         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
             ...         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
             ...         at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
             ...         at DD4T.Serialization.JSONSerializerService.Deserialize[T](String input)
             ...         at DD4T.Factories.PageFactory.GetIPageObject(String pageStringContent)
             ...         at DD4T.Factories.PageFactory.TryFindPage(String url, IPage& page)
             ...         at Indivirtual.DD4T.Mvc.Controllers.BasePageController.GetModelForPage(String PageId, PageType type)
             ...         at Indivirtual.SHARJAH24.Controllers.PageController.Page(String pageId)
             ...         at lambda_method(Closure , ControllerBase , Object[] )
             ...         at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
             ...         at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
             ...         at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
             ...         at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

The log file attached for your reference.

Appreciate your support and look forward to your help?

**Comment by ThijsBorst** [comment]
Which version of the templates are your using?

**Comment by avmgan** [comment]
We used DD4T.Templates.2.1.2 version

**Comment by ThijsBorst** [comment]
That Templates version is still built against NewtonSoft.Json 6.0.8 

Can you upgrade those too to the latest version? Those templates are built against NewtonSoft.Json 10.0.1 too. Don't forget to republish your pages. Please test before go-live of course...

**Comment by kpmrafeeq** [comment]
@ThijsBorst  So, do we need to update the template as well? my assumption was the issue is on the front end not occurring due to the template

**Comment by ThijsBorst** [comment]
I think it might have to do with both. So serializing certain content with newtonsoft json 6.0.8 which can't be read correctly by 10.0.1. It is trying to resolve a type, but somehow it is not working. 
Can you send me the json code that is in the database? I might be able to figure out where it goes wrong from that.

**Comment by avmgan** [comment]
We upgraded to DD4T.Templates.2.2.1 and keep you posted, if it's still persisted this error.

**Comment by avmgan** [comment]
Here is one of the page json output: (note that it's prepared after the  DD4T.Templates.2.2.1 upgrade)

H4sIAAAAAAAEAO1ZW0/bSBT+K5af49S3GOI3FkgXLYUIIrRSw4OJh8RbX7K+UCLEA6hctrt/YlWhXnbbLlpaqf/E/jd7ZjK2x47DAk1FK1VczJw5Puc71zkZDvgNtGcFlucuGSHidV4WpTlBVARZ7ciSLsu6rPE1vmXZyDUczGC5JtoH0qoRhO1ox7aCATLpy6IoSgL57oiiTr6Bs230UQc5Q5swHRBhy/shcrFaeMsIhlhgJRBZkKWOJOmqpqvNelOaA8ZHKDRMIzRaFrLNAEvcs9BT/FwbQyTLGr9l2BGC/ceA1TUtt4+B8Ns1fi1ykG/1sn0gYaUdy0EsbdVynyBz0XOGnovckN0iqjujIWhTavwivNz3/BFVj9VwqcHcFoAJ+JxpxQSWsOfoqiCpQkOSYe8nNHrq+Wam4YBfCTY8L+T1XcMOUA2WCztB6Bu9nLSEgp5vDcOxD6mFHDGRCMyJlNYx9j3XcyoBtI1wANRutwJ7t1uUs4HwnkkxU4e0DR9cVKRNxOkQDMmVK0pTkERZxdCs0EYlwIfbh0V+SZwXJHmeYV/0XMiicGw0MG/2BsgxcCJg5y3byIFdGpQI0nbXcpHJl0BoAiuS2P+A2wz9qBdGPuIe+l405FJTsJbJ9KM4frC93pOAycMinUnImeTgsrODTBOxWTPOyEw/WbJ1sGWZyAtmXgJijf+ZZlDqnAe9KAg9Ry+44LG0ndIptHLi45j/vxnrQ8vFaX9vdsg3sIOJ0HV5SQUXs1KaVyezMoXEpWJxMjLo1Ruir4Sb9yc2f1MS6/wFP5x9Bk02UVES69watB+OQVHRQ2WZtrCptuevf36bjf9KjuOXyVH8mkvOueQoOU3Ok9Os4RLfVHbaDGbWaScN7Hbp+3fvsMTdTATJko3eGI3aEGcQwoNbzACTh7smiCqeMuBwVyR8uCsN/voWXl0qklIolYfIRb5hZ7VBvEI3845C1qxfpgT2C3YYDJ9aVCrTrLdQlFVNsiL0AfJMNlkza0sbBbPfwNfH5CQ55ZKz+J/kjAMnPIs/gCPegivI4kX8Ln4Vv4wvx8t38OcHvPcKL5PT+H1yDqQ3HH7A/t/w8y9DgN+X8VW6OIo/kedzwkFeoJ4H0uv4Dyo2vog/0nDEF8D+WxWU5ATAf4LncQ4HAgfP0+Q5tuiccl3B8wzkX6YYrwDFJcj5MyW8iN8TwUA4id+O8SW/492L5BgvwUUZCQxOOepdvzv7c0gqZkm5o5XXE/GtTJhMaaaD9h0rRbCF/PFE3ihUGG4WeX1Bedc50qcOi6C1KXrZWp1rlCc+Kgn41ow9yP9dJm9TSkX/mpfuv4E1yKcTaGCKLmp6o1kXm3N36WAKnA1sBwOzrb6BQ8lh861+5JNVsaUB16YVgqZh27cgiOGo6LnyJutEsd68385Wia9qKMkZWz76NUJur9rMfJe1c+BFvj36WkxlMd6spd+uauVi1eISyZOKYuBSf3PUN5NFPG2Oyqvx+vbS9lEAD5Ky4yLLtsiAMsOR4fu88H1e+NbmhW92Wmh5tol8nCakfHukwLPCEgUorWKlyVpTkNnJQc0mh+tnD0Y+VjehIxOoiNzmwPB/MQayyi1sYLnrT118gfQZEm4y+bD+YS4216NwGIUtz3cM6HX8j51Hq1zLN/rOuAtde8HZ0HRVritzyp0uONMu9uU/l2dv3OyGU5nZDWdqYvpZe8qNplL+nD0NcLebS5zVlaYkieUBNztfysOwpsHkV30QbSAXSg1HZ3yAEWNXgqWRazhWL/PPug9c6y65/dRFfJJn15bk1vIWtdpoCOq0Us0HjHnlKypOZU4TNLVcnyvkvxOH/wErXDT/1xgAAA==

**Comment by kpmrafeeq** [comment]
@ThijsBorst , then it should occur every time, if we access this page again it gets serialized properly. It is very intermittent. I was wondering if the request getting timed out, will this have something to do with serialization ??

**Comment by arthurtheaquaboy** [comment]
Just an FYI we see this issue occur when under high loads, and when we start up a new application instance in Azure. We can't regularly replicate the issue. Some days we see it a lot (and it kills our site for 2-5 mins), and then resolves itself, and other times we can run weeks without seeing it.

**Comment by avmgan** [comment]
In our scenario in preview only used by content editors not used by public visitors no traffics on the website.

One think, I can highlight in our preview and live environment every 10mins there should be publishing activities happening.

It's very strange issue.

**Comment by kpmrafeeq** [comment]
Don't scary me Chris

**Comment by raerae1616** [comment]
We are also experiencing this intermittently also on a Site for us . . . 

We are using DXA v1.6, which of course uses DD4T and the GetPage() will randomly start encountering this error.  Our application does not recover once this error starts getting thrown; until we restart the web app it won't recover.  

The thread here still seems to be inconclusive . . . 

Does anyone have any updates that may help resolve this issue?
