### ISSUE TITLE
DD4T 2.0 DCP not de-serializing multi-value embeddable schema field

### ISSUE THREAD

**Issue by Vouzamo** [dd4t/DD4T.Core#104]
See full write up here: http://tridion.stackexchange.com/questions/16382/dd4t-2-0-dcp-not-de-serializing-multi-value-embeddable-schema-field

I was obtaining the `IComponent` via an `IComponentFactory` and using the `IViewModelFactory.BuildViewModel<T>(IComponent)` method.

This does NOT work.

If I instead use an `IComponentPresentationFactory` to obtain an `IComponentPresentation` and pass the `IComponentPresentation` to the `IViewModelFactory.BuildViewModel<T>(IComponentPresentation)` method this works correctly.

I can't even use the `IViewModelFactory.BuildViewModel<T>(IComponent)` method and pass the `IComponentPresentation.Component` property as this fails.

It seems that the model builder depends on something present outside the scope of the `IComponent` and/or the method which takes an `IComponent` may have a bug.

**Comment by Vouzamo** [comment]
#105 logged to address this issue with a bug fix.

**Comment by ThijsBorst** [comment]
PR accepted
