### ISSUE TITLE
Issue with defaultCacheAgent

### ISSUE THREAD

**Issue by kpmrafeeq** [dd4t/DD4T.Core#110]
with web 8.5 the communication message is different
Tridion communicates about cache expiry using a key like **1**:6:1120

**Comment by quirijnslings** [comment]
Fixed in DD4T.Caching.ApacheMQ 2.3.0.17-alpha, in combination with the latest dd4t-cachechannel java package.
See https://github.com/dd4t/DD4T.Caching.ApacheMQ/issues/6.
