### ISSUE TITLE
Feature request - .Net Core on the roadmap?

### ISSUE THREAD

**Issue by surrealcoder** [dd4t/DD4T.Core#120]
We are looking to change our primary web application that uses DD4T to .Net core from the regular 4.6 framework. But to do that we believe that DD4T needs to be compiled for .Net Core. So I'm asking if this is potentially on the roadmap?

**Comment by quirijnslings** [comment]
Hi @surrealcoder, just saw your issue (5 months too late, sorry). We have no plans for moving to .NET Core at the moment. DD4T is in maintenance mode now, because SDL would prefer people to use DXA. See http://dd4t.org/dxa2.html.
