### ISSUE TITLE
Improved caching with JMS-based invalidation

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/DD4T.Core#2]
There should be two cache agents:

- a 'piggy-back' agent, which checks the Tridion broker to find the last published date. It should do so EVERY TIME, and the monitors (like the current DefaultCacheAgent uses) must GO!!!

- an agent which is invalidated through JMS

Both agents should store in the same cache store. Preferably one which supports async invalidation (so when the item is to be invalidated, this is done in the background and the most recent item is returned until the new item is put in the cache store).

**Comment by ThijsBorst** [comment]
It's in progress by Quirijn.

**Comment by quirijnslings** [comment]
We need to add the java code to the repo.
