### ISSUE TITLE
ViewModelFactory must be limited in the assemblies which it searches

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/DD4T.Core#32]
Currently, all assemblies that are loaded in memory are searched looking for view models (i.e. classes implementing IViewModel). This is highly inefficient! For example, your app will go over all classes in assemblies like System, System.Web, DD4T.*, Tridion.*, etc..

We need to find a way to limit this to assemblies which are likely to contain the customer's view models. Possibilities are:

- Add 'ViewModelAssemblies' key to the configuration and have the ViewModelFactory search that
- Add a public property 'ViewModelAssemblies' to the ViewModelFactory interface so you can set it manually in the global.asax
- Hard-code the factory to NOT search in anything starting with System, DD4T or Tridion (on the plus side this requires no configuration at all, but it still leaves countless others like Newtonsoft, Autofac, .... )

**Comment by Ei8htSe7en** [comment]
Maybe I'm missing something but doesn't this method overload already address this: `void LoadViewModels(IEnumerable<Assembly> assemblies)`? 

This allows the caller to pass in the assemblies they want to search, and it only searches through those. Also it checks if its already seen an assembly before. This code is already in there

**Comment by quirijnslings** [comment]
I missed that, Josh. Problem seems to be though that the constructor calls LoadViewModels without any arguments, which means that all assemblies except the ones starting with 'Tridion' (and some other edge cases) are searched. 
I can call LoadViewModels(IEnumerable<Assembly> assemblies) but by that time all assemblies will have been loaded and searched already.

**Comment by Ei8htSe7en** [comment]
Ah ok I see now, the ctor is calling that method (doh!) &mdash; definitely shouldn't be doing that. I must have written that code for testing or something and forgot to remove it. I'll just remove that call in the ctor so it is up to the user to Load assemblies

**Comment by quirijnslings** [comment]
Fixed
