### ISSUE TITLE
PublicationId 0 (zero) is not supported over REST

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/DD4T.Core#36]
In the native Tridion pageproviders, it is possible to set the publication id to 0. This means: get the page by URL without looking at the publication id. This works fine in many implementations, especially if the publicationUrl property is unique per publication.

In the REST provider an error is thrown if the publication id is 0. Please make the behaviour consistent (by allowing 0 for the REST provider).

**Comment by sshibani** [comment]
Duplicate: https://github.com/dd4t/DD4T.RestService.WebApi/issues/5
