### ISSUE TITLE
Update website for release of 2.0 GA

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/DD4T.Core#51]

**Comment by rsleggett** [comment]
As discussed with Q. The following changes will be made:

 - Update website to make quote more prominent
 - Discuss with Ron
 - Add CTA for release and Web 8 in top slot.

Also update the wiki in parallel
 
 - Better organisation
 - Split between contributing and developing using the framework
 - Better information on Getting started.
 - Include information on ViewModels (inc 2 BaseControllers)
 - Link to Getting Started page direct from website.
