### ISSUE TITLE
Concurrency issue in DD4TConfiguration

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/DD4T.Core#62]
The DD4TConfiguration class is not entirely thread safe. This leads to errors like this:

10:47:35.24  Error    Global Error Handling (http://backstage.flydubai.com/en/ by 172.31.9.79)
             ...      System.ArgumentException (mscorlib)
             ...      An item with the same key has already been added.
             ...         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
             ...         at DD4T.Utils.DD4TConfiguration.GetExpirationForCacheRegion(String region)
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.FindCacheItemPolicy(String key, Object item, String region)
             ...         at DD4T.Utils.Caching.DefaultCacheAgent.Store(String key, String region, Object item, List`1 dependOnTcmUris)
             ...         at DD4T.Factories.PageFactory.TryFindPage(String url, IPage& page)
             ...         at DD4T.Mvc.Controllers.DD4TControllerBase.GetPage(String url)
             ...         at Indivirtual.Flydubai.Web.Controllers.PageController.PageModel(String url)

Solution: add locking and a double-if construction to make the code thread-safe.

**Comment by bharoodh** [comment]
I am getting this error in DXA upon first time access of a page. Subsequent requests works fine though. Where should I implement locking and double-if construction?

**Comment by albertromkes** [comment]
You could also use a ConcurrentDictionary for this. See the example code below (untested, replaces the existing method `GetExpirationForCacheRegion` in the `DD4TConfiguration` class):

```
public int GetExpirationForCacheRegion(string region)
{			
	return _expirationPerRegion.GetOrAdd(region, (cacheRegion => 
	{
		string regionCacheSetting = SafeGetConfigSettingAsString(string.Format(ConfigurationKeys.CacheSettingsPerRegion, cacheRegion));
		return !string.IsNullOrEmpty(regionCacheSetting) ? int.Parse(regionCacheSetting) : DefaultCacheSettings;
	}));
}
```

Make sure tho replace the `private Dictionary<string, int> _expirationPerRegion = new Dictionary<string, int>();` 

to:

`private ConcurrentDictionary<string, int> _expirationPerRegion = new ConcurrentDictionary<string, int>();`

**Comment by quirijnslings** [comment]
This was solved ages ago
