### ISSUE TITLE
Default RichtTextResovler does not Resolve Binary links

### ISSUE THREAD

**Issue by sshibani** [dd4t/DD4T.Core#72]
When a binary component is added as a component link to a RTF field in Tridion. The DefaultRichTextResolver used by the ViewModelAttribute does not resolve binary links.

Possible fix:

Inject BinaryFactory into DefaultRichTextResolver and resolve the binary link.

**Comment by Shiva85** [comment]
Does this issue happen when certain RTF components linking to binaries or all RTF components linking to binaries? I am currently seeing an issue for certain components but NOT all and tend to resolve when we make an edit and breaks sometime as well (random). Trying to isolate the issue but wanted some feedback as well.
