### ISSUE TITLE
Investigate the use of a Symbols server for debugging

### ISSUE THREAD

**Issue by ThijsBorst** [dd4t/DD4T.Core#78]
Debugging a dd4t application can be made easier with a Symbols server. Investigate what it takes to host such a Symbols server or that we create pdb files on release.

**Comment by ThijsBorst** [comment]
It seems that nuget has a solution for it with a Symbols flag. We need to generate pdb files on build and generate two packages (one for the symbols server), but it seems to be no problem. More info can be found here: http://docs.nuget.org/create/creating-and-publishing-a-symbol-package

Will need to test it out on one of the packages.

**Comment by DominicCronin** [comment]
This looks interesting... symbols and source... http://www.symbolsource.org/Public
