### ISSUE TITLE
Getting-started documentation should cover creating template metadata schemas

### ISSUE THREAD

**Issue by DominicCronin** [dd4t/DD4T.Core#83]
The getting started documentation does not currently cover creating schemas to allow for metadata on component templates and page templates in order to specify the view. 

This information is available as part of the article at http://remcorakers.nl/dd4t-development-environment/, but it should be part of the DD4T documentation

**Comment by quirijnslings** [comment]
Done. See https://github.com/dd4t/DD4T.Core/wiki/1.0-Getting-started-with-.NET.
Can I close?

**Comment by ThijsBorst** [comment]
@DominicCronin Can you respond?

**Comment by DominicCronin** [comment]
This is fixed. Sorry for the delay in responding.
