### ISSUE TITLE
ComponentPresentationFactory stores DCPs in the cache based on only the Component URI

### ISSUE THREAD

**Issue by arthurtheaquaboy** [dd4t/DD4T.Core#96]
We use the same component  in multiple places in our site, using different component templates. Each template is designed to  invoke a different Component View.

The current ComponentPresentationFactory stores the DCP in the cache using just the Component URI as a key. So only one DCP is actually stored in the cache. The means that we can't apply different Component Views to each DCP

```

        public bool TryGetComponentPresentation(out IComponentPresentation cp, string componentUri, string templateUri = "")
        {
            cp = null;

            string cacheKey = CacheKeyFactory.GenerateKeyFromUri(componentUri, CacheRegion);
            cp = (IComponentPresentation)CacheAgent.Load(cacheKey);
```

https://github.com/dd4t/DD4T.Core/blob/develop/source/DD4T.Factories/ComponentPresentationFactory.cs

**Comment by ThijsBorst** [comment]
Submitted a fix for this issue.

**Comment by ThijsBorst** [comment]
The code has been merged into develop. Can be closed on next release.
